theme: jekyll-theme-cayman
title: Martin Wind
google_analytics: UA-92418726-1
image: https://avatars2.githubusercontent.com/u/339631?v=3&s=460
stackoverflow: http://stackoverflow.com/story/windm
linkedin: https://www.linkedin.com/in/martin-wind-8b0289134/
github_user_page: https://github.com/mawi12345
